
POST http://localhost:5000/api/permission/create
Content-Type: application/json

{
    "name": "super admin",
    "permission": ["create", "update", "delete", "read"],
    "positission": ["create", "update", "delete", "read"],
    "room": ["create", "update", "delete", "read"],
    "single": ["create", "update", "delete", "read", "approve"],
    "singleType": ["create", "update", "delete", "read"],
    "user": ["create", "update", "delete", "read"]
}

