POST http://localhost:5000/api/Position/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYzM3YTA1OGEzNjVmY2NmZjljNDYiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBjaOG7qWMgdiIsInN0YXR1cyI6MSwicGVybWlzc2lvbiI6WyJyZWFkIl0sInBvc2l0aW9uIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwicm9vbSI6WyJyZWFkIl0sInNpbmdsZSI6WyJyZWFkIl0sInNpbmdsZVR5cGUiOlsicmVhZCJdLCJ1c2VyIjpbInJlYWQiLCJ1cGRhdGUiXSwiY3JlYXRlZEF0IjoiMjAyMy0xMC0wNFQwOTo1MjozMS4yODBaIiwidXBkYXRlZEF0IjoiMjAyMy0xMC0wNlQwODoyMDo1MC4xMzlaIiwiX192IjowfSwiaWF0IjoxNjk2NTgwNDgwfQ.d_sNER4v5QoSnb3PNrXw7GGg6rvwlai09Z3vguwVeDY

{
    "name": "Phê h",
    "room": "651cd84ef0cd55e83b306219"
    
}

###
# "name": "nhân viên",
#      "room": "651cd85cf0cd55e83b30621f"

###
GET  http://localhost:5000/api/Position/getall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYzM3YTA1OGEzNjVmY2NmZjljNDYiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBjaOG7qWMgdiIsInN0YXR1cyI6MSwicGVybWlzc2lvbiI6WyJyZWFkIl0sInBvc2l0aW9uIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwicm9vbSI6WyJyZWFkIl0sInNpbmdsZSI6WyJyZWFkIl0sInNpbmdsZVR5cGUiOlsicmVhZCJdLCJ1c2VyIjpbInJlYWQiLCJ1cGRhdGUiXSwiY3JlYXRlZEF0IjoiMjAyMy0xMC0wNFQwOTo1MjozMS4yODBaIiwidXBkYXRlZEF0IjoiMjAyMy0xMC0wNlQwODoyMDo1MC4xMzlaIiwiX192IjowfSwiaWF0IjoxNjk2NTgwNDgwfQ.d_sNER4v5QoSnb3PNrXw7GGg6rvwlai09Z3vguwVeDY


###
GET  http://localhost:5000/api/Position/getOne/651cddb5d0a47f5527b8d22e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYzM3YTA1OGEzNjVmY2NmZjljNDYiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBjaOG7qWMgdiIsInN0YXR1cyI6MSwicGVybWlzc2lvbiI6WyJyZWFkIl0sInBvc2l0aW9uIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwicm9vbSI6WyJyZWFkIl0sInNpbmdsZSI6WyJyZWFkIl0sInNpbmdsZVR5cGUiOlsicmVhZCJdLCJ1c2VyIjpbInJlYWQiLCJ1cGRhdGUiXSwiY3JlYXRlZEF0IjoiMjAyMy0xMC0wNFQwOTo1MjozMS4yODBaIiwidXBkYXRlZEF0IjoiMjAyMy0xMC0wNlQwODoyMDo1MC4xMzlaIiwiX192IjowfSwiaWF0IjoxNjk2NTgwNDgwfQ.d_sNER4v5QoSnb3PNrXw7GGg6rvwlai09Z3vguwVeDY

###
PUT http://localhost:5000/api/Position/update/651fc3aa058a365fccff9c50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFjZmUzZjk4NTA1MTNjODBiOTNkZmEiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFjZDc0NTEzMDU2YjRmOTRhY2Y4NzkiLCJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJzaW5nbGUiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSIsImFwcHJvdmUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1ODAxNDN9.ftUrP87zJqLVs2djUuKinz8xnzifMmp65-SAaX7UdTo

{
    "name": "Quản lý hồ sơ",
    "room": "651cd84ef0cd55e83b306219"
}

###
DELETE   http://localhost:5000/api/Position/delete/651fc3aa058a365fccff9c50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFjZmUzZjk4NTA1MTNjODBiOTNkZmEiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFjZDc0NTEzMDU2YjRmOTRhY2Y4NzkiLCJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJzaW5nbGUiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSIsImFwcHJvdmUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1ODAxNDN9.ftUrP87zJqLVs2djUuKinz8xnzifMmp65-SAaX7UdTo
