POST http://localhost:5000/api/room/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw

{
    "name": "Phòng 5",
    "description": ""
  
}


###
GET http://localhost:5000/api/room/getOne/651cd84ef0cd55e83b306219
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw


###
GET http://localhost:5000/api/room/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw



###
PUT http://localhost:5000/api/room/update/651fbdb3ba02fe686fcbfea1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw


{
    "name": "Phòng nhân sự",
    "description": ""
  
}
###
DELETE  http://localhost:5000/api/room/deleteRoom/651fbdb3ba02fe686fcbfea1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYmQ2NmJhMDJmZTY4NmZjYmZlOWMiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMzVkZjM0ZWQ2OGQ0MWJiMWQ5YmMiLCJuYW1lIjoiUXXhuqNuIGzDvSBwaMOybmcgYmFuIiwic3RhdHVzIjoxLCJwZXJtaXNzaW9uIjpbInJlYWQiXSwicG9zaXRpb24iOlsicmVhZCJdLCJyb29tIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwic2luZ2xlIjpbInJlYWQiXSwic2luZ2xlVHlwZSI6WyJyZWFkIl0sInVzZXIiOlsicmVhZCIsInVwZGF0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDA5OjUyOjMxLjI4MFoiLCJfX3YiOjB9LCJpYXQiOjE2OTY1NzkwNzB9.PNciiNtUf7P0nyBDtViLgy_zE1nT62RizEjWWMTVPDw
