POST http://localhost:5000/api/single/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkMGNlMDBjM2MxNmE0ZmNkMjE4MjYiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMDM1MjE4ZGE1MmZiYWI4N2IwMmYiLCJuYW1lIjoiUXXhuqNuIGzDvSB0w6BpIGtob-G6o24iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsicmVhZCJdLCJwb3NpdGlvbiI6WyJyZWFkIl0sInJvb20iOlsicmVhZCJdLCJzaW5nbGUiOlsicmVhZCJdLCJzaW5nbGVUeXBlIjpbInJlYWQiXSwidXNlciI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMDRUMDY6MTY6NTAuMjYxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTAtMDRUMDY6MTY6NTAuMjYxWiIsIl9fdiI6MH0sImlhdCI6MTY5NjY4OTIwM30.xPaOvLyaUI_CrUJ7cG88u2weuBAWP3R8qvAP1iDW4M4


{
  "name":"Đơn xin nghỉ phép việc -Phạm Văn Trường",
  "content":[
        {
            "key":"proposalGroup",
            "label":"Nhóm đề xuất",
            "value":"Đơn xin nghỉ phép",
            "required": true
        },
        {
            "key":"fullName",
            "label":"Họ Và tên",
            "value":"Phạm Văn Trường",
            "required": true
        },
        {
            "key":"room",
            "label":"bộ phận",
            "value":"651cd84ef0cd55e83b306219",
            "required": true
        },
        {
            "key":"startDay",
            "label":"Ngày bắt đầu làm việc",
            "value":"22/08/2023",
            "required": true
        },
        {
            "key":"position",
            "label":"chức vụ",
            "value":"651cddd30dc302c1dcdc40a0",
            "required": true
        },
        {
            "key":"TheLastWorkingDay",
            "label":"Ngày làm việc cuối cùng",
            "value":"7/10/2023",
            "required": true
        },
        {
            "key":"reasonForQuittingJob",
            "label":"Lí do nghỉ việc",
            "value":"Không phù hợp với công ty",
            "required": true
        }
       ],
    "singlesStyes":"65201f80c8dbc9e75ea177ac",
    "approver":"651cfe3f9850513c80b93dfa"
    
}


###
GET http://localhost:5000/api/single/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkMGNlMDBjM2MxNmE0ZmNkMjE4MjYiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMDM1MjE4ZGE1MmZiYWI4N2IwMmYiLCJuYW1lIjoiUXXhuqNuIGzDvSB0w6BpIGtob-G6o24iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsicmVhZCJdLCJwb3NpdGlvbiI6WyJyZWFkIl0sInJvb20iOlsicmVhZCJdLCJzaW5nbGUiOlsicmVhZCJdLCJzaW5nbGVUeXBlIjpbInJlYWQiXSwidXNlciI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMDRUMDY6MTY6NTAuMjYxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTAtMDRUMDY6MTY6NTAuMjYxWiIsIl9fdiI6MH0sImlhdCI6MTY5NjY4OTIwM30.xPaOvLyaUI_CrUJ7cG88u2weuBAWP3R8qvAP1iDW4M4



###
DELETE  http://localhost:5000/api/single/delete/652167830e23c32b832f72b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFjZmUzZjk4NTA1MTNjODBiOTNkZmEiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFjZDc0NTEzMDU2YjRmOTRhY2Y4NzkiLCJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJzaW5nbGUiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSIsImFwcHJvdmUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJfX3YiOjB9LCJpYXQiOjE2OTY2OTA1OTN9.ZbgdydDQOvjbo4p3PaIXx932HBA1V-JHe12FD7-vOMw

###
PUT  http://localhost:5000/api/single/update/65216e0f16fca99df2be7dff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFjZmUzZjk4NTA1MTNjODBiOTNkZmEiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFjZDc0NTEzMDU2YjRmOTRhY2Y4NzkiLCJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJzaW5nbGUiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSIsImFwcHJvdmUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJfX3YiOjB9LCJpYXQiOjE2OTY2OTA1OTN9.ZbgdydDQOvjbo4p3PaIXx932HBA1V-JHe12FD7-vOMw

{
  "name":"Đơn xin nghỉ  việc -Phạm Văn Trường",
  "content":[
        {
            "key":"proposalGroup",
            "label":"Nhóm đề xuất",
            "value":"Đơn xin nghỉ phép",
            "required": true
        },
        {
            "key":"fullName",
            "label":"Họ Và tên",
            "value":"Phạm Văn Trường",
            "required": true
        },
        {
            "key":"room",
            "label":"bộ phận",
            "value":"651cd84ef0cd55e83b306219",
            "required": true
        },
        {
            "key":"startDay",
            "label":"Ngày bắt đầu làm việc",
            "value":"22/08/2023",
            "required": true
        },
        {
            "key":"position",
            "label":"chức vụ",
            "value":"651cddd30dc302c1dcdc40a0",
            "required": true
        },
        {
            "key":"TheLastWorkingDay",
            "label":"Ngày làm việc cuối cùng",
            "value":"7/10/2023",
            "required": true
        },
        {
            "key":"reasonForQuittingJob",
            "label":"Lí do nghỉ việc",
            "value":"Không phù hợp với công ty",
            "required": true
        }
       ],
    "singlesStyes":"65201f80c8dbc9e75ea177ac",
    "approver":"651cfe3f9850513c80b93dfa"
    
}