POST http://localhost:5000/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFjZmUzZjk4NTA1MTNjODBiOTNkZmEiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFjZDc0NTEzMDU2YjRmOTRhY2Y4NzkiLCJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJwb3NpdGlvbiI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvb20iOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJzaW5nbGUiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSIsImFwcHJvdmUiXSwic2luZ2xlVHlwZSI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sInVzZXIiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJjcmVhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEwLTA0VDAzOjA4OjUzLjMzOVoiLCJfX3YiOjB9LCJpYXQiOjE2OTY2MDA2MDR9.1v3Y_tA83glkwGzLchPamHl31yCHOdKGT2bVaDxKEcI

{
    "name":"Phạm Văn Hai",
    "email":"hai@gmail.com",
    "password":"1",
    "room":"651cd84ef0cd55e83b306219",
    "permissions":"651d35df34ed68d41bb1d9bc",
    "positions":"651fc29d058a365fccff9c37"
    
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"1"
}
###
Put http://localhost:5000/api/users/update/651d0ce00c3c16a4fcd21826
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkMGNlMDBjM2MxNmE0ZmNkMjE4MjYiLCJwZXJtaXNzaW9ucyI6eyJfaWQiOiI2NTFkMDM1MjE4ZGE1MmZiYWI4N2IwMmYiLCJuYW1lIjoiUXXhuqNuIGzDvSB0w6BpIGtob-G6o24iLCJzdGF0dXMiOjEsInBlcm1pc3Npb24iOlsicmVhZCJdLCJwb3NpdGlvbiI6WyJyZWFkIl0sInJvb20iOlsicmVhZCJdLCJzaW5nbGUiOlsicmVhZCJdLCJzaW5nbGVUeXBlIjpbInJlYWQiXSwidXNlciI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sImNyZWF0ZWRBdCI6IjIwMjMtMTAtMDRUMDY6MTY6NTAuMjYxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTAtMDRUMDY6MTY6NTAuMjYxWiIsIl9fdiI6MH0sImlhdCI6MTY5NjQwNjg4MX0.0eTx7yWavTanixrVFPktpRW_NFr14lvV65kx50IUkL0

{
    "name":"Phạm Văn Trường",
    "email":"truong@gmail.com",
    "password":"1",
    "sex": "2",
    "phone":"0975128913",
    "birthday": "14/10/2001"
}